version: '3.8'

services:
  pinewood_app:
    build:
      context: .
      dockerfile: Dockerfile.combined
    ports:
      - "8088:8088"  # Main app
      - "84:84"      # Diag app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pinewoodstoredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=pinewoodstoreadmin
      - SPRING_DATASOURCE_PASSWORD=pinewoodstoreadmin2025
      - API_BASE_URL=http://localhost:8088
      - API_BASE_URL_DIAG=http://localhost:84
      - API_BASE_URL_PINEWOODSTORE=http://localhost:8088/welcome
      - CORS_ALLOWED_ORIGIN=http://localhost:8088/welcome
    volumes:
      - ./logs:/var/log/apps
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pinewoodstoredb
      - MYSQL_USER=pinewoodstoreadmin
      - MYSQL_PASSWORD=pinewoodstoreadmin2025
      - MYSQL_ROOT_PASSWORD=rootpinewoodstoreadmin2025
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "pinewoodstoreadmin", "-ppinewoodstoreadmin2025"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data: